### ISSUE TITLE
Migrate off camlp4

### ISSUE THREAD

**Issue by XVilka** [ygrek/extunix#32]
Camlp4 release for OCaml 4.08 is the last release ever - see the [official announcement](https://discuss.ocaml.org/t/the-end-of-camlp4/4216). It is recommended to port the code to use ppx (extension points), or any external parser (like mehrir, sedlex, ocamllex, ansgtrom, etc).

**Comment by glondu** [comment]
I had a look, and it turns out that extunix uses a camlp4 syntax extension `pa_here` to preprocess `src/extUnix.mlpp` in two ways:

- in the first one, it amounts to simple conditional compilation (whole blocks are kept or removed)
- in the second one, it amounts to keep everything, but rewrite externals in blocks that are removed by the first preprocessing

I believe ppx is the right replacement technology here.

**Comment by ygrek** [comment]
yes, I have it in the works

**Comment by ygrek** [comment]
oh, I see your PR, thanks!
